"""KITTI raw tracklet labels: 3D boxes with persistent track IDs, per frame.

`tracklet_labels.xml` is a Boost serialisation dump. Each `item` under
`<tracklets>` is one physical object, carrying fixed dimensions and a list of
per-frame poses starting at `first_frame`. Poses are in the VELODYNE frame with
the translation at the box's BOTTOM-CENTRE, and `rz` is yaw about the velodyne
z axis (`rx`, `ry` are 0 in every released drive).

These labels are used for two things and nothing else:
  1. object identity and class, for tracking metrics (MOTA / IDF1 / ID-switches)
  2. a cross-check on the LiDAR-derived range ground truth built in Phase 1

They are NOT used to bound a monocular estimate. An estimator scored against
labels it was given is not being measured.

Caveat that travels with every number computed from these: raw tracklets are not
the official KITTI *tracking* benchmark split, so tracking metrics here are not
directly comparable to that leaderboard. Same source recordings, different
annotation packaging. See docs/decisions.md D-004.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import dataclass
from functools import cached_property
from pathlib import Path

import numpy as np

from aps.kitti.calibration import Calibration

# tracklet <truncation> enum, from the KITTI raw devkit
TRUNC_IN_IMAGE, TRUNC_TRUNCATED, TRUNC_OUT_IMAGE, TRUNC_BEHIND_IMAGE = 0, 1, 2, 99

# tracklet <occlusion> enum
OCC_UNSET, OCC_VISIBLE, OCC_PARTLY, OCC_FULLY = -1, 0, 1, 2

# Classes this project reasons about. KITTI also labels 'Misc', 'Tram',
# 'Person (sitting)'; they are kept in the label set but never enter the FCW
# evaluation, because a class the detector was never trained to emit would
# score as a permanent false negative and quietly depress every recall number.
VEHICLE_CLASSES = frozenset({"Car", "Van", "Truck"})
VRU_CLASSES = frozenset({"Pedestrian", "Cyclist"})
FCW_CLASSES = VEHICLE_CLASSES | VRU_CLASSES


def _text(node: ET.Element, tag: str, default: str = "0") -> str:
    child = node.find(tag)
    return child.text if child is not None and child.text is not None else default


@dataclass(frozen=True)
class TrackletBox:
    """One labelled 3D box, at one frame."""

    frame: int
    track_id: int
    object_type: str
    center_velo: np.ndarray  # (3,) bottom-centre, velodyne frame
    dims_lwh_m: tuple[float, float, float]
    yaw_rad: float  # about velodyne z
    truncation: int
    occlusion: int

    @cached_property
    def corners_velo(self) -> np.ndarray:
        """(8, 3) box corners in the velodyne frame; bottom four first."""
        length, width, height = self.dims_lwh_m
        x = length / 2.0
        y = width / 2.0
        local = np.array(
            [
                [+x, +y, 0.0],
                [+x, -y, 0.0],
                [-x, -y, 0.0],
                [-x, +y, 0.0],
                [+x, +y, height],
                [+x, -y, height],
                [-x, -y, height],
                [-x, +y, height],
            ]
        )
        c, s = np.cos(self.yaw_rad), np.sin(self.yaw_rad)
        rot = np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])
        return local @ rot.T + self.center_velo

    def ranges_m(self, calib: Calibration) -> tuple[float, float]:
        """(near_face_range_m, center_range_m) -- both longitudinal, in metres.

        `near_face` is the minimum depth over the eight corners: the distance to
        the closest surface of the object. That is the quantity a forward
        collision warning is about (the gap that closes to zero), and it is what
        the monocular pinhole relation actually recovers, since the bounding box
        is generated by the visible face.

        `center` is the depth of the box centroid. It is reported alongside
        because it is what most papers mean by "distance to object", and the two
        differ by roughly half a vehicle length -- ~2.2 m for a car, which is
        larger than most of the error sources this project measures. Comparing
        an estimator against the wrong one of these is a silent 2 m bias.
        See docs/decisions.md D-003.
        """
        corners_rect = calib.velo_to_rect0(self.corners_velo)
        _, depths = calib.project_rect0(corners_rect)
        centroid = self.corners_velo.mean(axis=0)[None, :]
        _, center_depth = calib.project_rect0(calib.velo_to_rect0(centroid))
        return float(depths.min()), float(center_depth[0])

    def box_2d(
        self, calib: Calibration, clip: bool = True, min_depth_m: float = 0.5
    ) -> np.ndarray | None:
        """Axis-aligned 2D box [x1, y1, x2, y2] in pixels, or None if not imageable.

        Returns None when any corner falls at or behind the image plane: such a
        box has no finite projection, and the amodal extent of an object the
        camera is partly inside of is not something a 2D box can express. Those
        frames are excluded from detection metrics and counted, never silently
        clamped to the image border -- a clamped box scores as a confident wrong
        answer instead of an honest abstention.
        """
        corners_rect = calib.velo_to_rect0(self.corners_velo)
        uv, depth = calib.project_rect0(corners_rect)
        if (depth < min_depth_m).any() or not np.isfinite(uv).all():
            return None
        box = np.array([uv[:, 0].min(), uv[:, 1].min(), uv[:, 0].max(), uv[:, 1].max()])
        if clip:
            w, h = calib.image_size[2]
            box = np.array(
                [
                    np.clip(box[0], 0, w - 1),
                    np.clip(box[1], 0, h - 1),
                    np.clip(box[2], 0, w - 1),
                    np.clip(box[3], 0, h - 1),
                ]
            )
            if box[2] - box[0] < 1 or box[3] - box[1] < 1:
                return None
        return box


@dataclass
class Tracklet:
    """One physical object across the frames it appears in."""

    track_id: int
    object_type: str
    dims_lwh_m: tuple[float, float, float]
    first_frame: int
    boxes: list[TrackletBox]

    def __len__(self) -> int:
        return len(self.boxes)


def load_tracklets(path: Path) -> list[Tracklet]:
    """Parse `tracklet_labels.xml`. Track IDs are the item order in the file."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"no tracklet labels at {path}")

    root = ET.parse(path).getroot()
    container = root.find("tracklets")
    if container is None:
        raise ValueError(f"{path}: no <tracklets> element")

    tracklets: list[Tracklet] = []
    for track_id, item in enumerate(container.findall("item")):
        obj_type = _text(item, "objectType", "Unknown")
        height = float(_text(item, "h"))
        width = float(_text(item, "w"))
        length = float(_text(item, "l"))
        first = int(_text(item, "first_frame"))

        poses = item.find("poses")
        boxes: list[TrackletBox] = []
        if poses is not None:
            for offset, pose in enumerate(poses.findall("item")):
                boxes.append(
                    TrackletBox(
                        frame=first + offset,
                        track_id=track_id,
                        object_type=obj_type,
                        center_velo=np.array(
                            [
                                float(_text(pose, "tx")),
                                float(_text(pose, "ty")),
                                float(_text(pose, "tz")),
                            ]
                        ),
                        dims_lwh_m=(length, width, height),
                        yaw_rad=float(_text(pose, "rz")),
                        truncation=int(float(_text(pose, "truncation"))),
                        occlusion=int(float(_text(pose, "occlusion", "-1"))),
                    )
                )
        tracklets.append(Tracklet(track_id, obj_type, (length, width, height), first, boxes))
    return tracklets


def boxes_by_frame(
    tracklets: list[Tracklet],
    classes: frozenset[str] | None = None,
    drop_out_of_image: bool = True,
) -> dict[int, list[TrackletBox]]:
    """Invert tracklets into a frame -> boxes index.

    `drop_out_of_image` removes poses the annotators marked OUT_IMAGE or
    BEHIND_IMAGE. Those objects exist in the world but are not in the picture,
    and counting them as missed detections would make every recall number a lie
    about the camera's field of view rather than about the detector.
    """
    out: dict[int, list[TrackletBox]] = {}
    for t in tracklets:
        if classes is not None and t.object_type not in classes:
            continue
        for b in t.boxes:
            if drop_out_of_image and b.truncation in (TRUNC_OUT_IMAGE, TRUNC_BEHIND_IMAGE):
                continue
            out.setdefault(b.frame, []).append(b)
    return out
