"""Regenerate the headline figure: monocular range error vs range.

    python tools/plot_range_curve.py --split val
    python tools/plot_range_curve.py --split test --out docs/figures/range_error_test.png

The project's central claim is a curve, not a number, so the curve is a committed
artefact regenerated by this committed script from a committed evaluation
artefact (`artifacts/range_eval_<split>.npz`). No notebook, no hand-placed
annotation.

What the figure must show to be honest, and does:

  * **both estimators**, because they cross -- contact-point wins near,
    size-prior far, and a single line would hide that;
  * **the credible envelope**, shaded, so the eye lands on the band the project
    vouches for rather than on the flattering part of the curve;
  * **the sample count per bin**, printed, because the far bins are thin;
  * **the ground-truth floor**, so a reader can see how much of the error is the
    ruler's own -- read from THIS split's own ruler artefact, never a constant
    carried over from another split;
  * **the median alongside the mean**, because the two diverge exactly where the
    error is long-tailed, and the test split is where that stopped being
    academic (docs/decisions.md D-025);
  * **the envelope labelled by where it was declared**, so a test-split figure
    cannot be read as if the band had been re-earned on held-out data.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
BINS = [(0, 10), (10, 20), (20, 30), (30, 50)]
LABELS = ["0–10", "10–20", "20–30", "30–50"]
ESTIMATORS = [
    ("contact_point", "contact-point  (ground plane)", "#1f77b4", "o"),
    ("size_prior", "size-prior  (class height)", "#d62728", "s"),
]
ENVELOPE = (10.0, 30.0)  # declared on val in Phase 3 (D-015); shown, not re-earned
SPREAD_GATE_M = 1.5


def ruler_floor_pct(split: str, centres: list[float]) -> list[float] | None:
    """The split's own LiDAR ruler error, as a percentage of range.

    Read from `artifacts/range_gt_<split>.npz` rather than hardcoded, because a
    figure that plots one split's data over another split's error floor is
    exactly the class of mistake this project keeps catching: a comparison
    quietly made against the wrong denominator.
    """
    src = REPO / "artifacts" / f"range_gt_{split}.npz"
    if not src.exists():
        return None
    g = np.load(src, allow_pickle=True)
    truth = g["label_near_m"].astype(float)
    pred = g["shrink_p20"].astype(float)
    # The usable-tier filter is part of the ruler, not a detail of its report.
    # Without it this picks up occluded boxes the ruler abstains on -- whose
    # error is the OCCLUDER's (MAE 11.9 m, D-010) -- and draws a "floor" three
    # times too high, understating how much of the curve above is really the
    # monocular estimator's own error.
    usable = np.isin(g["tier"], ["strict", "relaxed"])
    keep = usable & np.isfinite(pred) & (g["spread_m"].astype(float) <= SPREAD_GATE_M)
    out = []
    for (lo, hi), c in zip(BINS, centres, strict=True):
        m = keep & (truth >= lo) & (truth < hi)
        out.append(100 * np.abs(pred[m] - truth[m]).mean() / c if m.sum() >= 10 else np.nan)
    return out


def mape_by_bin(truth: np.ndarray, pred: np.ndarray) -> tuple[list[float], list[float], list[int]]:
    """Mean and median absolute percentage error per bin, plus counts.

    Both, always. On val they agree and the median looks redundant; on test the
    mean moved 8.1 points at 20-30 m while the median moved 1.1, and the figure
    that showed only the mean would have reported a collapse that never happened
    to the typical object.
    """
    mean_, med, counts = [], [], []
    for lo, hi in BINS:
        m = np.isfinite(pred) & (truth >= lo) & (truth < hi)
        counts.append(int(m.sum()))
        if m.sum() < 10:
            mean_.append(np.nan)
            med.append(np.nan)
            continue
        ape = 100 * np.abs(pred[m] - truth[m]) / truth[m]
        mean_.append(float(ape.mean()))
        med.append(float(np.median(ape)))
    return mean_, med, counts


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--split", default="val")
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument(
        "--artifact",
        type=Path,
        default=None,
        help="evaluation .npz to plot; defaults to artifacts/range_eval_<split>.npz",
    )
    ap.add_argument(
        "--stamp",
        default=None,
        help="provenance line drawn on the figure -- required when --artifact is given, "
        "so a figure made from a non-default artefact can never be mistaken for the "
        "current one",
    )
    args = ap.parse_args()

    if args.artifact and not args.stamp:
        ap.error("--artifact requires --stamp naming what that artefact is")

    src = args.artifact or REPO / "artifacts" / f"range_eval_{args.split}.npz"
    d = np.load(src, allow_pickle=True)
    truth = d["gt_range"]
    centres = [(lo + hi) / 2 for lo, hi in BINS]

    held_out = args.split == "test"
    fig, ax = plt.subplots(figsize=(8.2, 5.0), dpi=160)
    ax.axvspan(*ENVELOPE, color="#2ca02c", alpha=0.10, zorder=0)
    ax.text(
        20, 38.4,
        "envelope declared on val: 10–30 m at ≤15% MAPE"
        + ("\nshown here as the claim under test" if held_out else ""),
        ha="center", va="top", fontsize=8.5, color="#2f6f2f",
    )  # fmt: skip

    ruler_pct = ruler_floor_pct(args.split, centres)
    if ruler_pct is not None:
        ax.fill_between(centres, 0, ruler_pct, color="0.5", alpha=0.35, zorder=1)
        ax.plot(centres, ruler_pct, color="0.35", lw=1, ls=":", zorder=2,
                label=f"LiDAR ground-truth floor ({args.split})")  # fmt: skip

    # Which curve is on top varies by bin and by split, so the label offset has
    # to follow the data. Fixing it per estimator collided the moment the two
    # crossed inside a bin.
    series = {key: mape_by_bin(truth, d[key])[0] for key, *_ in ESTIMATORS}

    for key, label, colour, marker in ESTIMATORS:
        values, medians, _ = mape_by_bin(truth, d[key])
        in_bin = sum(int(((truth >= lo) & (truth < hi)).sum()) for lo, hi in BINS)
        valid = int(np.isfinite(d[key][(truth >= BINS[0][0]) & (truth < BINS[-1][1])]).sum())
        ax.plot(centres, values, marker=marker, color=colour, lw=2, ms=7, zorder=3,
                label=f"{label} — {100 * valid / max(in_bin, 1):.0f}% valid")  # fmt: skip
        ax.plot(centres, medians, marker=marker, color=colour, lw=1.2, ms=4, ls="--",
                alpha=0.65, zorder=3, label=f"{label.split('  ')[0]} — median")  # fmt: skip
        for i, (x, y) in enumerate(zip(centres, values, strict=True)):
            if not np.isfinite(y):
                continue
            others = [s[i] for k, s in series.items() if k != key and np.isfinite(s[i])]
            dy = 9 if not others or y >= max(others) else -15
            ax.annotate(f"{y:.1f}%", (x, y), textcoords="offset points", xytext=(0, dy),
                        ha="center", fontsize=8, color=colour)  # fmt: skip

    ax.axhline(15, color="0.3", lw=0.8, ls="--")
    ax.text(3.0, 15.5, "15% MAPE", ha="left", fontsize=8, color="0.3")

    # Ground-truthable detections per bin -- the denominator both estimators are
    # scored on. Taking it from whichever estimator happened to be drawn last
    # would report one curve's abstentions under both.
    for (lo, hi), x in zip(BINS, centres, strict=True):
        n = int(((truth >= lo) & (truth < hi)).sum())
        ax.annotate(f"N={n}", (x, 0.6), ha="center", fontsize=7.5, color="0.35")

    ax.set_xlabel("ground-truth range (m)")
    ax.set_ylabel("range error, MAPE (%)")
    ax.set_title(
        f"Monocular range error vs range — KITTI {args.split}"
        + (" (HELD OUT)" if held_out else "")
        + f", N={len(truth)} ground-truthable detections",
        fontsize=11,
    )
    ax.set_xticks(centres)
    ax.set_xticklabels(LABELS)
    ax.set_ylim(0, 40)  # headroom so the legend cannot hide the 0-10 m points
    ax.set_xlim(2, 50)
    ax.grid(alpha=0.25)
    ax.legend(loc="upper right", fontsize=8, framealpha=0.95)
    fig.text(
        0.01,
        0.028,
        "Monocular camera only · offline, open-loop · LiDAR used as ground truth, never as input.",
        fontsize=7,
        color="0.35",
    )
    fig.text(
        0.01,
        0.008,
        "Detected AND ground-truthable objects only (~33% of labels), so every value is a lower bound."
        "  Dashed = median APE; its gap to the mean is the tail.",
        fontsize=7,
        color="0.35",
    )
    if args.stamp:
        ax.text(
            0.5, 0.075, args.stamp, transform=ax.transAxes, ha="center", fontsize=8,
            color="#8a4b00", bbox={"facecolor": "#fff3e0", "edgecolor": "#e0a060", "pad": 3},
        )  # fmt: skip
    fig.tight_layout(rect=(0, 0.05, 1, 1))

    out = args.out or REPO / "docs" / "figures" / f"range_error_{args.split}.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out)
    print(f"wrote {out}  (from {src.name})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
